
import java.awt.HeadlessException;
import java.io.File;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RAY
 */
public class Autos extends javax.swing.JDialog {

    /**
     * Creates new form Autos
     */
    public Autos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        BuscarCliente();
        BuscarAuto(codauto);
        this.setBounds(0, 0, 1602, 700);
        setLocationRelativeTo(null);
    }

    Conexion conect = new Conexion("ejeautos");
Connection con = null;
Statement st = null;
String encontrado;
String codauto = "1";
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbAutos = new javax.swing.JComboBox<>();
        jcbColor = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        foto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jcbClientes = new javax.swing.JComboBox<>();
        jtfanio = new javax.swing.JTextField();
        jtfMarca = new javax.swing.JTextField();
        jtfMatricula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(956, 646));
        setMinimumSize(new java.awt.Dimension(956, 646));
        setPreferredSize(new java.awt.Dimension(960, 650));
        getContentPane().setLayout(null);

        jcbAutos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbAutosItemStateChanged(evt);
            }
        });
        jcbAutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbAutosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jcbAutosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jcbAutosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jcbAutosMouseReleased(evt);
            }
        });
        jcbAutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAutosActionPerformed(evt);
            }
        });
        getContentPane().add(jcbAutos);
        jcbAutos.setBounds(1260, 380, 120, 30);

        jcbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Negro", "Azul", "Verde", "Gris", "Blanco", "Naranja", "Otro" }));
        getContentPane().add(jcbColor);
        jcbColor.setBounds(1000, 330, 150, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Autos");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1210, 380, 60, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida 46px.png"))); // NOI18N
        jButton2.setText("Salir");
        jButton2.setContentAreaFilled(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida 64px.png"))); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1330, 450, 100, 100);

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar 46px.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar 64px.png"))); // NOI18N
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(880, 450, 100, 100);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar 46.png"))); // NOI18N
        jButton4.setText("Modificar");
        jButton4.setContentAreaFilled(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar.png"))); // NOI18N
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jButton4);
        jButton4.setBounds(980, 450, 110, 100);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpio 46px.png"))); // NOI18N
        jButton6.setText("Limpiar");
        jButton6.setContentAreaFilled(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpio 64px.png"))); // NOI18N
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(1100, 450, 90, 100);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Screenshot_76.png"))); // NOI18N
        jButton7.setText("Eliminar");
        jButton7.setContentAreaFilled(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar 64.png"))); // NOI18N
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(1210, 450, 100, 100);

        foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(foto);
        foto.setBounds(1130, 130, 320, 170);

        jButton1.setText("imagen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1270, 330, 75, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Color");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(950, 330, 50, 40);

        jcbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbClientesActionPerformed(evt);
            }
        });
        getContentPane().add(jcbClientes);
        jcbClientes.setBounds(1020, 390, 120, 30);

        jtfanio.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jtfanio.setText("Carro");
        getContentPane().add(jtfanio);
        jtfanio.setBounds(960, 240, 150, 40);

        jtfMarca.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jtfMarca.setText("Marca del carro");
        jtfMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(jtfMarca);
        jtfMarca.setBounds(960, 190, 150, 40);

        jtfMatricula.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jtfMatricula.setText("Matricula del carro");
        getContentPane().add(jtfMatricula);
        jtfMatricula.setBounds(960, 140, 150, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Cliente");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(950, 390, 60, 30);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/home.png"))); // NOI18N
        jButton8.setText("Inicio");
        jButton8.setBorder(null);
        jButton8.setContentAreaFilled(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(1470, 20, 90, 80);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Carro");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(850, 240, 110, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Matricula");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(850, 140, 110, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Marca");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(850, 190, 110, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion"));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(860, 120, 260, 170);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(860, 310, 590, 10);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(860, 440, 580, 10);

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seccionAutos.jpg"))); // NOI18N
        fondo.setText("Fondo");
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 1620, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents
String direccionFoto;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
JFileChooser fc = new JFileChooser("C:\\imagenes autos\\");
int seleccion = fc.showOpenDialog(this);
if(seleccion == JFileChooser.APPROVE_OPTION){
File f = fc.getSelectedFile();
Icon icon= new ImageIcon(f.getAbsolutePath());
direccionFoto = f.getAbsolutePath();
foto.setIcon(icon);
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtfMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMarcaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        limpiar();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
crearAuto();        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jcbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbClientesActionPerformed

        codauto = jcbClientes.getSelectedItem().toString();
        BuscarAuto(codauto);
        limpiar();
    }//GEN-LAST:event_jcbClientesActionPerformed

    private void jcbAutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAutosActionPerformed
if(jcbAutos.getSelectedItem()!=null){
String auto2[]=jcbAutos.getSelectedItem().toString().split(" ");
        BuscarAuto2(auto2[0]); 
}
           

    }//GEN-LAST:event_jcbAutosActionPerformed

    private void jcbAutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbAutosMouseClicked
         // TODO add your handling code here:
    }//GEN-LAST:event_jcbAutosMouseClicked

    private void jcbAutosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbAutosMousePressed
      // TODO add your handling code here:
    }//GEN-LAST:event_jcbAutosMousePressed

    private void jcbAutosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbAutosItemStateChanged
       // TODO add your handling code here:
    }//GEN-LAST:event_jcbAutosItemStateChanged

    private void jcbAutosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbAutosMouseReleased
         // TODO add your handling code here:
    }//GEN-LAST:event_jcbAutosMouseReleased

    private void jcbAutosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbAutosMouseExited
       // TODO add your handling code here:
    }//GEN-LAST:event_jcbAutosMouseExited

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Principal().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed
String cliente;
    private void BuscarCliente() {
        Conexion conect = new Conexion("ejeautos");
        try {
            String senten = "SELECT * FROM clientes WHERE estado LIKE 'Activo'";
            encontrado = "NO";            
            con = conect.getConexion();
            st = con.createStatement();
            ResultSet rs = st.executeQuery(senten);
            

            while (rs.next()) {
                cliente = rs.getString("codcliente")+" "+rs.getString("nombre");
                jcbClientes.addItem(cliente);
                encontrado = "SI";
                
            }

            if (encontrado.equals("NO")) {
                JOptionPane.showMessageDialog(null, "NO ENCONTRADO", "ATENCION!", JOptionPane.ERROR_MESSAGE);
            }
            con.close();
            
        } catch (HeadlessException | SQLException x) {
            System.out.println(x);}
    }
    
    
    
    public void crearAuto() {
        try {
            con = conect.getConexion();
            //COLOQUE EN LA SENTENCIA SQL EL NOMBRE DE SU BD Y LOS NOMBRE DE LOS CAMPOS
            String sql = "INSERT INTO autos (codauto,matricula,marca,color,anio,foto,idduenio,estado) VALUES (?,?,?,?,?,?,?,?)";
            PreparedStatement ps = conect.getConexion().prepareStatement(sql);
            //COLOQUE LOS NOMBRES DE SUS CUADROS DE DIALOGO (JTEXTFIELD)
            ps.setInt(1, 0);
            ps.setString(2, jtfMatricula.getText());
            ps.setString(3, jtfMarca.getText());
            ps.setString(4, jcbColor.getSelectedItem().toString());
            ps.setString(5, jtfanio.getText());  
            ps.setString(6, direccionFoto); 
            String combo[]=jcbClientes.getSelectedItem().toString().split(" ");
            ps.setString(7, combo[0]); 
            ps.setString(8, "Activo"); 
            ps.execute();
            JOptionPane.showMessageDialog(null, "REGISTRO INGRESADO CORRECTAMENTE", "ATENCION!", 1);
            limpiar();
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "REGISTRO NO SE PUDO GUARDAR", "ATENCION!" + e, 0);
            System.out.println(e);
        }
    }
    String auto;
    private void BuscarAuto(String cod) {
        Conexion conect = new Conexion("ejeautos");
        jcbAutos.removeAllItems();
        try {
            String senten = "SELECT * FROM autos WHERE idduenio = '"+cod+"'";
            encontrado = "NO";            
            con = conect.getConexion();
            st = con.createStatement();
            ResultSet rs = st.executeQuery(senten);
            

            while (rs.next()) {
                auto = rs.getString("codauto")+" "+rs.getString("matricula");                
                jcbAutos.addItem(auto);
                jtfMarca.setText(rs.getString("marca"));
                jtfMatricula.setText(rs.getString("matricula"));
                jtfanio.setText(rs.getString("anio"));
                jcbColor.setSelectedItem(rs.getString("color"));
                Icon icon= new ImageIcon(rs.getString("foto"));
                foto.setIcon(icon);
                encontrado = "SI";
                
            }

            if (encontrado.equals("NO")) {
                JOptionPane.showMessageDialog(null, "NO ENCONTRADO", "ATENCION!", JOptionPane.ERROR_MESSAGE);
            }
            con.close();
            
        } catch (HeadlessException | SQLException x) {
            System.out.println(x);}
    }
    
    private void BuscarAuto2(String cod) {
        limpiar();
        Conexion conect = new Conexion("ejeautos");
        
        try {
            String senten = "SELECT * FROM autos WHERE codauto = '"+cod+"'";
            encontrado = "NO";            
            con = conect.getConexion();
            st = con.createStatement();
            ResultSet rs = st.executeQuery(senten);
            

            while (rs.next()) {
                
                jtfMarca.setText(rs.getString("marca"));
                jtfMatricula.setText(rs.getString("matricula"));
                jtfanio.setText(rs.getString("anio"));
                jcbColor.setSelectedItem(rs.getString("color"));
                Icon icon= new ImageIcon(rs.getString("foto"));
                foto.setIcon(icon);
                encontrado = "SI";
                
            }

            if (encontrado.equals("NO")) {
                JOptionPane.showMessageDialog(null, "NO ENCONTRADO", "ATENCION!", JOptionPane.ERROR_MESSAGE);
            }
            con.close();
            
        } catch (HeadlessException | SQLException x) {
            System.out.println(x);}
    }
    
public void limpiar(){
jtfMarca.setText("");
jtfMatricula.setText("");
jtfanio.setText("");
foto.setIcon(null);
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Autos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Autos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Autos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Autos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Autos dialog = new Autos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel foto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> jcbAutos;
    private javax.swing.JComboBox<String> jcbClientes;
    private javax.swing.JComboBox<String> jcbColor;
    private javax.swing.JTextField jtfMarca;
    private javax.swing.JTextField jtfMatricula;
    private javax.swing.JTextField jtfanio;
    // End of variables declaration//GEN-END:variables
}
